service: vegetable-prices
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2
  httpApi:
    cors: true


  environment:
    PRICES_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-prices
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PRICES_DYNAMODB_TABLE}"

functions:
  getCommodityPricesFromWeb:
    handler: handler.getCommodityPricesFromWeb
    events:
      - httpApi:
          path: /prices
          method: GET
  getPricingInformation:
    handler: handler.getPricingInformation
    events:
      - httpApi:
          path: /price/{dateVal}
          method: GET          
resources:
  Resources:
    PricesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
           - AttributeName: id
             KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1        
        TableName: ${self:provider.environment.PRICES_DYNAMODB_TABLE}    

